compiler-rt: Undef _TIME_BITS along with _FILE_OFFSET_BITS on linux
On 32bit systems using 64bit time_t build fails because
_FILE_OFFSET_BITS is undefined here but _TIME_BITS is still set to 64

Fixes
/usr/include/features-time64.h:26:5: error: "_TIME_BITS=64 is allowed
 only with _FILE_OFFSET_BITS=64"
| #   error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
|     ^
| 1 error generated.

Also avoid LFS64 functions on musl

Upstream-Status: Pending
Signed-off-by: Khem Raj <raj.khem@gmail.com>