compiler-rt: Undef _TIME_BITS along with _FILE_OFFSET_BITS in sanitizers
On 32bit systems using 64bit time_t build fails because
_FILE_OFFSET_BITS is undefined here but _TIME_BITS is still set to 64

Fixes
In file included from compiler-rt/lib/sanitizer_common/sanitizer_procmaps_solaris.cpp:17:
In file included from compiler-rt/lib/sanitizer_common/sanitizer_platform.h:25:
In file included from /usr/include/features.h:393:
/usr/include/features-time64.h:26:5: error: "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
    ^
1 error generated.

Upstream-Status: Submitted [https://reviews.llvm.org/D144514]
Signed-off-by: Khem Raj <raj.khem@gmail.com>