compiler-rt: Link scudo with SANITIZER_CXX_ABI_LIBRARIES
If SANITIZER_CXX_ABI_LIBRARIES is set then link scudo with it, this
fixes build time errors like

projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.armhf.dir/sanitizer_posix_libcdep.cpp.o: in function `__sanitizer::UnsetAlternateSignalStack()':
| sanitizer_posix_libcdep.cpp:(.text+0x3d2): undefined reference to `__cxa_guard_acquire'

Signed-off-by: Khem Raj <raj.khem@gmail.com>